In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [ ]:
import sys
print("Python Executeable :", sys.executable)
print("Python version:", sys.version)

In [23]:
project_dir = Path.cwd().parent

if project_dir.name == "notebook":
    project_dir = project_dir.parent

file_path = project_dir / "data" / "raw" / "smartphones.csv"

df = pd.read_csv(file_path)

print("Data Load Successfully")

Data Load Successfully

In [28]:
df.head(5)

,brand_name,model,price,avg_rating,5G_or_not,processor_brand,num_cores,processor_speed,battery_capacity,fast_charging_available,...,internal_memory,screen_size,refresh_rate,num_rear_cameras,os,primary_camera_rear,primary_camera_front,extended_memory_available,resolution_height,resolution_width
0,apple,Apple iPhone 11,38999,7.3,0,bionic,6.0,2.65,3110.0,0,...,64,6.1,60,2,ios,12.0,12.0,0,1792,828
1,apple,Apple iPhone 11 (128GB),46999,7.5,0,bionic,6.0,2.65,3110.0,0,...,128,6.1,60,2,ios,12.0,12.0,0,1792,828
2,apple,Apple iPhone 11 Pro Max,109900,7.7,0,bionic,6.0,2.65,3500.0,1,...,64,6.5,60,3,ios,12.0,12.0,0,2688,1242
3,apple,Apple iPhone 12,51999,7.4,1,bionic,6.0,3.10,NaN,0,...,64,6.1,60,2,ios,12.0,12.0,0,2532,1170
4,apple,Apple iPhone 12 (128GB),55999,7.5,1,bionic,6.0,3.10,NaN,0,...,128,6.1,60,2,ios,12.0,12.0,0,2532,1170

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 980 entries, 0 to 979
Data columns (total 22 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   brand_name                 980 non-null    str
 1   model                      980 non-null    str
 2   price                      980 non-null    int64
 3   avg_rating                 879 non-null    float64
 4   5G_or_not                  980 non-null    int64
 5   processor_brand            960 non-null    str
 6   num_cores                  974 non-null    float64
 7   processor_speed            938 non-null    float64
 8   battery_capacity           969 non-null    float64
 9   fast_charging_available    980 non-null    int64
 10  fast_charging              769 non-null    float64
 11  ram_capacity               980 non-null    int64
 12  internal_memory            980 non-null    int64
 13  screen_size                980 non-null    float64
 14  refresh_rate               980 non-null    int64
 15  num_rear_cameras           980 non-null    int64
 16  os                         966 non-null    str
 17  primary_camera_rear        980 non-null    float64
 18  primary_camera_front       975 non-null    float64
 19  extended_memory_available  980 non-null    int64
 20  resolution_height          980 non-null    int64
 21  resolution_width           980 non-null    int64
dtypes: float64(8), int64(10), str(4)
memory usage: 168.6 KB

In [27]:
df.describe(include = "all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
brand_name,980,46,xiaomi,134,NaN,NaN,NaN,NaN,NaN,NaN,NaN
model,980,980,Apple iPhone 11,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
price,980.0,NaN,NaN,NaN,32520.504082,39531.812669,3499.0,12999.0,19994.5,35491.5,650000.0
avg_rating,879.0,NaN,NaN,NaN,7.825825,0.740285,6.0,7.4,8.0,8.4,8.9
5G_or_not,980.0,NaN,NaN,NaN,0.560204,0.496616,0.0,0.0,1.0,1.0,1.0
processor_brand,960,13,snapdragon,413,NaN,NaN,NaN,NaN,NaN,NaN,NaN
num_cores,974.0,NaN,NaN,NaN,7.772074,0.836845,4.0,8.0,8.0,8.0,8.0
processor_speed,938.0,NaN,NaN,NaN,2.427217,0.46409,1.2,2.05,2.3,2.84,3.22
battery_capacity,969.0,NaN,NaN,NaN,4817.748194,1009.540054,1821.0,4500.0,5000.0,5000.0,22000.0
fast_charging_available,980.0,NaN,NaN,NaN,0.854082,0.353205,0.0,1.0,1.0,1.0,1.0
fast_charging,769.0,NaN,NaN,NaN,46.126138,34.27787,10.0,18.0,33.0,66.0,240.0
ram_capacity,980.0,NaN,NaN,NaN,6.560204,2.744378,1.0,4.0,6.0,8.0,18.0
internal_memory,980.0,NaN,NaN,NaN,141.036735,107.134516,8.0,64.0,128.0,128.0,1024.0
screen_size,980.0,NaN,NaN,NaN,6.536765,0.349162,3.54,6.5,6.58,6.67,8.03
refresh_rate,980.0,NaN,NaN,NaN,92.256122,28.988052,60.0,60.0,90.0,120.0,240.0
num_rear_cameras,980.0,NaN,NaN,NaN,2.814286,0.776441,1.0,2.0,3.0,3.0,4.0
os,966,3,android,909,NaN,NaN,NaN,NaN,NaN,NaN,NaN
primary_camera_rear,980.0,NaN,NaN,NaN,50.319286,33.000968,2.0,24.0,50.0,64.0,200.0
primary_camera_front,975.0,NaN,NaN,NaN,16.589744,10.876944,0.0,8.0,16.0,16.0,60.0
extended_memory_available,980.0,NaN,NaN,NaN,0.630612,0.482885,0.0,0.0,1.0,1.0,1.0
resolution_height,980.0,NaN,NaN,NaN,2214.663265,516.484254,480.0,1612.0,2400.0,2408.0,3840.0
resolution_width,980.0,NaN,NaN,NaN,1075.852041,290.164931,480.0,1080.0,1080.0,1080.0,2460.0

In [30]:
print("Rows: ",df.shape[0])
print("Column: ", df.shape[1])

print(df.head())

Rows:  980
Column:  22
  brand_name                    model   price  avg_rating  5G_or_not  \
0      apple          Apple iPhone 11   38999         7.3          0
1      apple  Apple iPhone 11 (128GB)   46999         7.5          0
2      apple  Apple iPhone 11 Pro Max  109900         7.7          0
3      apple          Apple iPhone 12   51999         7.4          1
4      apple  Apple iPhone 12 (128GB)   55999         7.5          1

  processor_brand  num_cores  processor_speed  battery_capacity  \
0          bionic        6.0             2.65            3110.0
1          bionic        6.0             2.65            3110.0
2          bionic        6.0             2.65            3500.0
3          bionic        6.0             3.10               NaN
4          bionic        6.0             3.10               NaN

   fast_charging_available  ...  internal_memory  screen_size  refresh_rate  \
0                        0  ...               64          6.1            60
1                        0  ...              128          6.1            60
2                        1  ...               64          6.5            60
3                        0  ...               64          6.1            60
4                        0  ...              128          6.1            60

   num_rear_cameras   os  primary_camera_rear primary_camera_front  \
0                 2  ios                 12.0                 12.0
1                 2  ios                 12.0                 12.0
2                 3  ios                 12.0                 12.0
3                 2  ios                 12.0                 12.0
4                 2  ios                 12.0                 12.0

   extended_memory_available  resolution_height  resolution_width
0                          0               1792               828
1                          0               1792               828
2                          0               2688              1242
3                          0               2532              1170
4                          0               2532              1170

[5 rows x 22 columns]

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 980 entries, 0 to 979
Data columns (total 22 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   brand_name                 980 non-null    str
 1   model                      980 non-null    str
 2   price                      980 non-null    int64
 3   avg_rating                 879 non-null    float64
 4   5G_or_not                  980 non-null    int64
 5   processor_brand            960 non-null    str
 6   num_cores                  974 non-null    float64
 7   processor_speed            938 non-null    float64
 8   battery_capacity           969 non-null    float64
 9   fast_charging_available    980 non-null    int64
 10  fast_charging              769 non-null    float64
 11  ram_capacity               980 non-null    int64
 12  internal_memory            980 non-null    int64
 13  screen_size                980 non-null    float64
 14  refresh_rate               980 non-null    int64
 15  num_rear_cameras           980 non-null    int64
 16  os                         966 non-null    str
 17  primary_camera_rear        980 non-null    float64
 18  primary_camera_front       975 non-null    float64
 19  extended_memory_available  980 non-null    int64
 20  resolution_height          980 non-null    int64
 21  resolution_width           980 non-null    int64
dtypes: float64(8), int64(10), str(4)
memory usage: 168.6 KB

In [45]:
stat_sum = df.describe(include="all").T
stat_sum

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
brand_name,980,46,xiaomi,134,NaN,NaN,NaN,NaN,NaN,NaN,NaN
model,980,980,Apple iPhone 11,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
price,980.0,NaN,NaN,NaN,32520.504082,39531.812669,3499.0,12999.0,19994.5,35491.5,650000.0
avg_rating,879.0,NaN,NaN,NaN,7.825825,0.740285,6.0,7.4,8.0,8.4,8.9
5G_or_not,980.0,NaN,NaN,NaN,0.560204,0.496616,0.0,0.0,1.0,1.0,1.0
processor_brand,960,13,snapdragon,413,NaN,NaN,NaN,NaN,NaN,NaN,NaN
num_cores,974.0,NaN,NaN,NaN,7.772074,0.836845,4.0,8.0,8.0,8.0,8.0
processor_speed,938.0,NaN,NaN,NaN,2.427217,0.46409,1.2,2.05,2.3,2.84,3.22
battery_capacity,969.0,NaN,NaN,NaN,4817.748194,1009.540054,1821.0,4500.0,5000.0,5000.0,22000.0
fast_charging_available,980.0,NaN,NaN,NaN,0.854082,0.353205,0.0,1.0,1.0,1.0,1.0
fast_charging,769.0,NaN,NaN,NaN,46.126138,34.27787,10.0,18.0,33.0,66.0,240.0
ram_capacity,980.0,NaN,NaN,NaN,6.560204,2.744378,1.0,4.0,6.0,8.0,18.0
internal_memory,980.0,NaN,NaN,NaN,141.036735,107.134516,8.0,64.0,128.0,128.0,1024.0
screen_size,980.0,NaN,NaN,NaN,6.536765,0.349162,3.54,6.5,6.58,6.67,8.03
refresh_rate,980.0,NaN,NaN,NaN,92.256122,28.988052,60.0,60.0,90.0,120.0,240.0
num_rear_cameras,980.0,NaN,NaN,NaN,2.814286,0.776441,1.0,2.0,3.0,3.0,4.0
os,966,3,android,909,NaN,NaN,NaN,NaN,NaN,NaN,NaN
primary_camera_rear,980.0,NaN,NaN,NaN,50.319286,33.000968,2.0,24.0,50.0,64.0,200.0
primary_camera_front,975.0,NaN,NaN,NaN,16.589744,10.876944,0.0,8.0,16.0,16.0,60.0
extended_memory_available,980.0,NaN,NaN,NaN,0.630612,0.482885,0.0,0.0,1.0,1.0,1.0
resolution_height,980.0,NaN,NaN,NaN,2214.663265,516.484254,480.0,1612.0,2400.0,2408.0,3840.0
resolution_width,980.0,NaN,NaN,NaN,1075.852041,290.164931,480.0,1080.0,1080.0,1080.0,2460.0

In [41]:
missing_report = pd.DataFrame({
    "missing_count": df.isna().sum(),
    "missing_percentage": (df.isna().mean()*100).round(2) 
})

missing_report.sort_values(
    "missing_count",
    ascending = False
)
print(missing_report
      )

                           missing_count  missing_percentage
brand_name                             0                0.00
model                                  0                0.00
price                                  0                0.00
avg_rating                           101               10.31
5G_or_not                              0                0.00
processor_brand                       20                2.04
num_cores                              6                0.61
processor_speed                       42                4.29
battery_capacity                      11                1.12
fast_charging_available                0                0.00
fast_charging                        211               21.53
ram_capacity                           0                0.00
internal_memory                        0                0.00
screen_size                            0                0.00
refresh_rate                           0                0.00
num_rear_cameras                       0                0.00
os                                    14                1.43
primary_camera_rear                    0                0.00
primary_camera_front                   5                0.51
extended_memory_available              0                0.00
resolution_height                      0                0.00
resolution_width                       0                0.00

In [43]:
print("Exact Duplicated rows: ", df.duplicated().sum())

Exact Duplicated rows:  0

In [44]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 980 entries, 0 to 979
Data columns (total 22 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   brand_name                 980 non-null    str
 1   model                      980 non-null    str
 2   price                      980 non-null    int64
 3   avg_rating                 879 non-null    float64
 4   5G_or_not                  980 non-null    int64
 5   processor_brand            960 non-null    str
 6   num_cores                  974 non-null    float64
 7   processor_speed            938 non-null    float64
 8   battery_capacity           969 non-null    float64
 9   fast_charging_available    980 non-null    int64
 10  fast_charging              769 non-null    float64
 11  ram_capacity               980 non-null    int64
 12  internal_memory            980 non-null    int64
 13  screen_size                980 non-null    float64
 14  refresh_rate               980 non-null    int64
 15  num_rear_cameras           980 non-null    int64
 16  os                         966 non-null    str
 17  primary_camera_rear        980 non-null    float64
 18  primary_camera_front       975 non-null    float64
 19  extended_memory_available  980 non-null    int64
 20  resolution_height          980 non-null    int64
 21  resolution_width           980 non-null    int64
dtypes: float64(8), int64(10), str(4)
memory usage: 168.6 KB

In [46]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
price,980.0,32520.504082,39531.812669,3499.00,12999.00,19994.50,35491.50,650000.00
avg_rating,879.0,7.825825,0.740285,6.00,7.40,8.00,8.40,8.90
5G_or_not,980.0,0.560204,0.496616,0.00,0.00,1.00,1.00,1.00
num_cores,974.0,7.772074,0.836845,4.00,8.00,8.00,8.00,8.00
processor_speed,938.0,2.427217,0.464090,1.20,2.05,2.30,2.84,3.22
battery_capacity,969.0,4817.748194,1009.540054,1821.00,4500.00,5000.00,5000.00,22000.00
fast_charging_available,980.0,0.854082,0.353205,0.00,1.00,1.00,1.00,1.00
fast_charging,769.0,46.126138,34.277870,10.00,18.00,33.00,66.00,240.00
ram_capacity,980.0,6.560204,2.744378,1.00,4.00,6.00,8.00,18.00
internal_memory,980.0,141.036735,107.134516,8.00,64.00,128.00,128.00,1024.00
screen_size,980.0,6.536765,0.349162,3.54,6.50,6.58,6.67,8.03
refresh_rate,980.0,92.256122,28.988052,60.00,60.00,90.00,120.00,240.00
num_rear_cameras,980.0,2.814286,0.776441,1.00,2.00,3.00,3.00,4.00
primary_camera_rear,980.0,50.319286,33.000968,2.00,24.00,50.00,64.00,200.00
primary_camera_front,975.0,16.589744,10.876944,0.00,8.00,16.00,16.00,60.00
extended_memory_available,980.0,0.630612,0.482885,0.00,0.00,1.00,1.00,1.00
resolution_height,980.0,2214.663265,516.484254,480.00,1612.00,2400.00,2408.00,3840.00
resolution_width,980.0,1075.852041,290.164931,480.00,1080.00,1080.00,1080.00,2460.00

Check binary columns

In [48]:
flag_columns = [
    "5G_or_not",
    "fast_charging_available",
    "extended_memory_available"
]
for col in flag_columns:
    print(f"\n{col}")
    print(df[col].value_counts(dropna = False))

5G_or_not
5G_or_not
1    549
0    431
Name: count, dtype: int64

fast_charging_available
fast_charging_available
1    837
0    143
Name: count, dtype: int64

extended_memory_available
extended_memory_available
1    618
0    362
Name: count, dtype: int64


Check missing values together

In [ ]:
missing = df.isna().sum()  # it will show with the intire columns name data
incomeplete_rows = df.isna().any(axis =1).sum()

print("Missing Values: ",missing.sum())  # here count the whole missing column name data
print("Rows with at least one missing Values: ", incomeplete_rows)
print("Complete rows: ",(~df.isna().any(axis=1)).sum())

Missing Values:  410
Rows with at least one missing Values:  302
Complete rows:  678

Investigate missing fast-charging specifications

In [53]:
df.groupby(
    "fast_charging_available",
    dropna=False
)["fast_charging"].agg(
    total_rows = "size",
    missing_values = lambda s: s.isna().sum(),
    available_values = lambda s: s.notna().sum()
    
)

                         total_rows  missing_values  available_values
fast_charging_available
0                               143             143                 0
1                               837              68               769

In [55]:
#check binary Columns
flag_columns = [
     "5G_or_not",
     "fast_charging_available",
     "extended_memory_available"

]

for col in flag_columns:
    print(f"\n{col}")
    print(df[col].value_counts(dropna=False))

5G_or_not
5G_or_not
1    549
0    431
Name: count, dtype: int64

fast_charging_available
fast_charging_available
1    837
0    143
Name: count, dtype: int64

extended_memory_available
extended_memory_available
1    618
0    362
Name: count, dtype: int64

In [56]:
missing = df.isna().sum()
print("Missing Value: ",missing.sum())

Missing Value:  410

In [57]:
incomplete_rows = df.isna().any(axis=1).sum()
print("Atleast ine missing values: ",incomplete_rows)

Atleast ine missing values:  302

In [58]:
print("Complete Rows: ", (~df.isna().any(axis=1)).sum())

Complete Rows:  678

In [60]:
# Find repeated combinations
model_duplicates = df.duplicated(
    subset=["brand_name","model"],
    keep = False
)

df.loc[
    model_duplicates,
    ["brand_name","model","price"]
].sort_values(["brand_name","model"])

Empty DataFrame
Columns: [brand_name, model, price]
Index: []

In [61]:
# Count the repeated combinations
repeated_rows = df.duplicated(
    subset=["brand_name","model"],
    keep=False
)

print("Rows belonging to repeated  combination:",repeated_rows.sum())

print(
    "distinct repeated brand/model combination: ",
    df.loc[repeated_rows,["brand_name","model"]].drop_duplicates().shape[0]
)

Rows belonging to repeated  combination: 0
distinct repeated brand/model combination:  0

In [62]:
# Investigate differences in price

df.loc[repeated_rows].groupby(
    ["brand_name","model"]
).agg(
    records = ("price","size"),
    unique_prices = ("price","nunique"),
    minimum_prices = ("price","min"),
    maximum_prices = ("price","max")
).sort_values("records",ascending=False)

Empty DataFrame
Columns: [records, unique_prices, minimum_prices, maximum_prices]
Index: []